### PR TITLE
An attempt at buffering, introduces permanent 479 sample latency

### PR DESCRIPTION
**Pull request by kode54**
Hope this helps a bit, I don't know if it works, I don't have an AU host installed to test it. I'll queue up Logic Pro X to install.

### CODE REVIEW

**Comment by williamleuschner** [comment]
Ouch, it definitely does not work and makes Apple's demo AU host play extremely loud clipping noises in my headphones, see if you can get it to load in Logic Pro X. I still haven't figured out what I'm doing wrong that causes AU Lab and `auval` to reject it. The demo AU host project does less validation and will happily feed samples into a broken AU for funzies.

**Comment by kode54** [comment]
Hol' up. I've got some changes for this. I have to bang them out before I can get some sleep.

**Comment by kode54** [comment]
There, please try that. It should function significantly better.

**Comment by williamleuschner** [comment]
Cool, AU Lab just doesn't work for v3 Audio Units. Apple's demo v3 filter AU won't load either, with the same error (`kAudioUnitErr_CannotDoInCurrentContext` or `-10863`). So that testing avenue is gone. I'll continue testing with the Demo v3 AU host application, and see if I can identify the cause of the horrific screeching.

**Comment by williamleuschner** [comment]
I've been reading through this code for about an hour and I'm not convinced I understand what it does, or that it successfully buffers things. The noise that I'm hearing when I run the AU sounds a lot like unallocated memory garbage. I'm going to try to implement a crappy version of this AU in `main` which just zero-pads, so that I can more fully understand how data comes in and goes out. Once I get that down, I can take another look at this.

**Pull request closed without merging**
